version = 0.1
[default.deploy.parameters]
stack_name = "aws-starter-sam-app"
#resolve_s3 = true
s3_prefix = "aws-starter-sam-app"
s3_bucket = "sample-project-trw"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
